### ISSUE TITLE
Hyphenated words cannot be aligned

### ISSUE THREAD

**Issue by strob** [lowerquality/gentle#11]
```get_matched_kaldi_sequence``` returns words with hyphens intact, while the alignment returns hyphenated words as separate tokens. Probably, ```get_matched_kaldi_sequence``` should return hyphenated words as separate tokens, and then a post-processing step can re-merge (or leave separate) such words.

**Comment by maxhawkins** [comment]
After 8f7649d the alignment will keep hyphenated words hyphenated if they're in the vocabulary. Does this change this issue?

**Comment by strob** [comment]
Still an issue. Many chains of words can be hyphenated together into valid English. I suppose we would implicitly resolve this issue once we add pronunciation support to OOV words.

**Comment by maxhawkins** [comment]
One solution would be to switch to using text offsets to link tokens to the source text:

```
"lower-quality"
=> {token: "lower", start: 0, end: 5}
=> {token: "quality", start: 6, end: 13}
```

Then when outputting you can just match up the tokens with the offsets in the original transcript.

That also leaves you the flexibility to do transformations on the token text or ignore metadata in the text while preserving it in the output:

```
"[Act 1]
Hermanstraße"
=> {token: "hermanstrasse", start: ..., end : ...}
```

I'll implement this later if I find some time.

**Comment by maxhawkins** [comment]
Ug. It's Python's utf-8 handling. Working on it...
