### ISSUE TITLE
Impossible phones count

### ISSUE THREAD

**Issue by SviMik** [lowerquality/gentle#120]
Is it a bug, or this is normal behavior to have 12 phones in word "a"? :)
That's a very... complicated "a" I'd say :)

     {
      "alignedWord": "a",
      "case": "success",
      "end": 0.7,
      "endOffset": 10,
      "phones": [
        {
          "duration": 0.03,
          "phone": "ey_B"
        },
        {
          "duration": 0.03,
          "phone": "f_I"
        },
        {
          "duration": 0.03,
          "phone": "ao_I"
        },
        {
          "duration": 0.03,
          "phone": "r_I"
        },
        {
          "duration": 0.03,
          "phone": "t_I"
        },
        {
          "duration": 0.03,
          "phone": "uw_I"
        },
        {
          "duration": 0.03,
          "phone": "w_I"
        },
        {
          "duration": 0.03,
          "phone": "ah_I"
        },
        {
          "duration": 0.04,
          "phone": "n_I"
        },
        {
          "duration": 0.03,
          "phone": "t_I"
        },
        {
          "duration": 0.03,
          "phone": "uw_I"
        },
        {
          "duration": 0.05,
          "phone": "ey_I"
        },
        {
          "duration": 0.04,
          "phone": "t_E"
        }
      ],
      "start": 0.27,
      "startOffset": 9,
      "word": "a"
    },

**Comment by strob** [comment]
It's a bug :)
I think it comes from a phoneme dictionary that was used by Kaldi
developers to train the language model. I have been investigating how to
resolve this issue.

**Comment by strob** [comment]
This is now fixed (see #124)
