### ISSUE TITLE
Package gentle in singularity

### ISSUE THREAD

**Issue by Liontooth** [lowerquality/gentle#127]
Gentle's dmg package works great for OS X, but installing from source often fails. My colleagues report that "Download the source code and run ./install.sh” isn't currenly working on either mac or linux, in part because of problems compiling Kaldi. These issues can of course be resolved one by one, but a useful alternative would be to package gentle using singularity (http://singularity.lbl.gov/).

**Comment by strob** [comment]
Singularity looks very interesting!

Either way: the installation issues need to be addressed. I'm curious for bug reports about the compilation failures. Are they "clean" installs of Gentle or updates from git that are failing?

Thanks!
-RMO

**Comment by strob** [comment]
I think that the adding a few ```clean``` commands to Kaldi's build should help it rebuild reliably after upgrades.
