### ISSUE TITLE
Tests Broken

### ISSUE THREAD

**Issue by maxhawkins** [lowerquality/gentle#14]
The tests fail for me using the most recent build. I think the golden master needs to be updated.

**Comment by strob** [comment]
Honestly: the golden master doesn't make any sense to me. But yes, it would need to be updated to a slightly-modified JSON format.

**Comment by maxhawkins** [comment]
I think it makes a lot of sense to have a high-level integration test like this. When I pulled your recent changes I was able to quickly see if there were any problems by running the test. Having a quick indication of whether the code works or not is really important when deploying to a new environment or months down the line when we can't remember how the code works.

I'm having some issues with the C++ compilation and can't regenerate the JSON, which is why I filed an issue rather than updating it myself. Would you mind updating to the latest version?

**Comment by maxhawkins** [comment]
Thanks!
