### ISSUE TITLE
Crash on Enable Full Transcription

### ISSUE THREAD

**Issue by pixeldrift** [lowerquality/gentle#143]
Version 0.10.1

I'm attempting to set up Gentle for use with autoEdit2. However, every time I click the "Enable full transcription" button it immediately crashes.

**Comment by strob** [comment]
Hi! Thanks for the bug report. It seems like there was an SSL problem on
the server, which has now been resolved. Please try again and let me know
if you see any further problems.

**Comment by tomasdms** [comment]
I'm experiencing the exact same problem. every time I click the "Enable full transcription" button it immediately crashes. 

Running macOS Mojave. Is there a fix to this?
