### ISSUE TITLE
Any document to help understand how gentle works?

### ISSUE THREAD

**Issue by twmht** [lowerquality/gentle#154]
Is there any document to help us understand how gentle works?

for example, in aeneas (https://github.com/readbeyond/aeneas/blob/master/wiki/HOWITWORKS.md), they explains how aeneas works.

**Comment by wkranti** [comment]
Gentle is built on top of Kaldi.First you should know how to use tools in Kaldi .
you should also know how speech recognition hierarchy works.
one way to understand how Gentle works is look into scripts and you will be able to know how Gentle 
works.Information related to task is mentioned inside  scripts.
