### ISSUE TITLE
Exception when using gentle online

### ISSUE THREAD

**Issue by hbake001** [lowerquality/gentle#161]
When I upload a wav file and run the alignment it gave me the following exception 

web.Server Traceback (most recent call last):
exceptions.OSError: [Errno 28] No space left on device: '/lockers/interlace_vol/src/gentle/webdata/transcriptions/ae9e03c5'
/usr/local/lib/python2.7/dist-packages/twisted/web/server.py:190 in process
189                    self._encoder = encoder
190            self.render(resrc)
191        except:
/usr/local/lib/python2.7/dist-packages/twisted/web/server.py:241 in render
240        try:
241            body = resrc.render(self)
242        except UnsupportedMethod as e:
/usr/local/lib/python2.7/dist-packages/twisted/web/resource.py:250 in render
249            raise UnsupportedMethod(allowedMethods)
250        return m(request)
251
serve.py:158 in render_POST
157        outdir = os.path.join(self.transcriber.data_dir, 'transcriptions', uid)
158        os.makedirs(outdir)
159
/usr/lib/python2.7/os.py:157 in makedirs
156            return
157    mkdir(name, mode)
158
exceptions.OSError: [Errno 28] No space left on device: '/lockers/interlace_vol/src/gentle/webdata/transcriptions/ae9e03c5'

**Comment by strob** [comment]
fixed - thanks!
