### ISSUE TITLE
Python Command Line Error

### ISSUE THREAD

**Issue by ghunkins** [lowerquality/gentle#168]
I am trying to using the direct Python source code interface to the run the basic example. Here are my steps:
(1) Clone the repository `git clone https://github.com/lowerquality/gentle.git`
(2) Run the installation script `./install.sh`
(3) Run the example command `python align.py examples/data/lucier.mp3 examples/data/lucier.txt`

Here is the error I'm receiving:
```Gregorys-MacBook-Pro:gentle ghunk$ python align.py examples/data/lucier.mp3 examples/data/lucier.txt
Traceback (most recent call last):
  File "align.py", line 49, in <module>
    resources = gentle.Resources()
  File "/Users/ghunk/Desktop/FUN/Elon/gentle/gentle/resources.py", line 19, in __init__
    require_dir(self.proto_langdir)
  File "/Users/ghunk/Desktop/FUN/Elon/gentle/gentle/resources.py", line 16, in require_dir
    raise RuntimeError("No resource directory %s.  Check %s environment variable?" % (path, ENV_VAR))
RuntimeError: No resource directory /Users/ghunk/Desktop/FUN/Elon/gentle/exp.  Check GENTLE_RESOURCES_ROOT environment variable?
```

Can anyone help with this? There are other scripts to run, but this is not included in the README description. Many thanks.

I am using the latest git version and am running macOS High Sierra 10.13.4.

**Comment by ghunkins** [comment]
I found a similar error here: https://github.com/lowerquality/gentle/issues/128. Following the instructions there solved this for me.

**Comment by markgwaps04** [comment]
Not working @ghunkins

**Comment by markgwaps04** [comment]
> I found a similar error here: #128. Following the instructions there solved this for me.

I'm done installing Twisted==16 but nothing happen

**Comment by PhotonNikko** [comment]
> I found a similar error here: #128. Following the instructions there solved this for me.

Could you open this issue again? I got the same error.

**Comment by bongblender** [comment]
do anyone have any solution to this..

**Comment by Yixin-Shen-1218** [comment]
Could you open this issue again? I got the same error.
