### ISSUE TITLE
Install on Centos7

### ISSUE THREAD

**Issue by spinicrus** [lowerquality/gentle#169]
Hello, thanks for gentle!

I'm trying to install on centos 7, installed dependencies with yum install, here is my install.sh:

```
#!/bin/bash

set -e
git submodule init
git submodule update

#./install_deps.sh
pip install .
(cd ext && ./install_kaldi.sh)
./install_models.sh
./install_language_model.sh
cd ext && make depend -j 2 && make -j 2
```

But somewhre in the make process this happens (after ./install_language_model.sh is executed):

```
make[1]: Leaving directory `/root/src/gentle/ext/kaldi/src/util'
g++ -rdynamic   k3.o kaldi/src/online2/kaldi-online2.a kaldi/src/ivector/kaldi-ivector.a kaldi/src/nnet3/kaldi-nnet3.a kaldi/src/chain/kaldi-chain.a kaldi/src/nnet2/kaldi-nnet2.a kaldi/src/lat/kaldi-lat.a kaldi/src/decoder/kaldi-decoder.a kaldi/src/cudamatrix/kaldi-cudamatrix.a kaldi/src/feat/kaldi-feat.a kaldi/src/transform/kaldi-transform.a kaldi/src/gmm/kaldi-gmm.a kaldi/src/hmm/kaldi-hmm.a kaldi/src/tree/kaldi-tree.a kaldi/src/matrix/kaldi-matrix.a kaldi/src/fstext/kaldi-fstext.a kaldi/src/util/kaldi-util.a kaldi/src/base/kaldi-base.a   /root/src/gentle/ext/kaldi/tools/openfst/lib/libfst.a /root/src/gentle/ext/kaldi/tools/OpenBLAS/install/lib/libopenblas.a -lgfortran -lm -lpthread -ldl  -o k3
m3.cc: In function 'int main(int, char**)':
m3.cc:174:28: error: no matching function for call to 'AddSelfLoops(kaldi::TransitionModel&, std::vector<int>&, float&, bool, bool, fst::VectorFst<fst::ArcTpl<fst::TropicalWeightTpl<float> > >*)'
                   &hclg_fst);
                            ^
m3.cc:174:28: note: candidates are:
In file included from kaldi/src/fstext/pre-determinize.h:94:0,
                 from kaldi/src/fstext/fstext-utils-inl.h:29,
                 from kaldi/src/fstext/fstext-utils.h:448,
                 from kaldi/src/fstext/context-fst-inl.h:23,
                 from kaldi/src/fstext/context-fst.h:535,
                 from m3.cc:1:
```
and later on:

```
make: *** [m3.o] Error 1
make: *** Waiting for unfinished jobs....
kaldi/src/ivector/kaldi-ivector.a(ivector-extractor.o): In function `kaldi::IvectorExtractor::ComputeDerivedVars()':
/root/src/gentle/ext/kaldi/src/ivector/ivector-extractor.cc:198: undefined reference to `kaldi::g_num_threads'
kaldi/src/ivector/kaldi-ivector.a(ivector-extractor.o): In function `kaldi::IvectorExtractorStats::IvectorExtractorStats(kaldi::IvectorExtractor const&, kaldi::IvectorExtractorStatsOptions const&)':
/root/src/gentle/ext/kaldi/src/ivector/ivector-extractor.cc:807: undefined reference to `kaldi::Mutex::Mutex()'
```

Any advice?
(by the way, the the latest cuda (9.2 as of writing this) is not supported by gentle's kaldi i guess)

Thanks a lot.

**Comment by strob** [comment]
You’ll probably get better debugging output if you remove the -j flags from
Make.

Cuda support is very new and not well tested. You may want to disable it.

**Comment by spinicrus** [comment]
Removing -j makes no diff at terminal output. Actually added that thinking that itll compile faster,  was getting tired of tries.
Concerning cuda support, i figured that & just mentioning. Thanks!

**Comment by strob** [comment]
Hm. I think the `AddSelfLoops` function changed in a recent version of Kaldi. I've updated the submodule version and the compilation seems to be working now. Re-open the issue if you're still having problems.

**Comment by spinicrus** [comment]
Wonderful, kaldi makes it ok and with cuda support enabled, no less :)
Unfortunately, /ext make process gives this:

```
k3.cc:62:28: error: no type named 'OnlineNnet3DecodingConfig' in namespace 'kaldi'
void ConfigDecoding(kaldi::OnlineNnet3DecodingConfig& config) {
                    ~~~~~~~^
k3.cc:99:15: error: no member named 'SetVerbose' in 'kaldi::CuDevice'
    cu_device.SetVerbose(true);
    ~~~~~~~~~ ^
k3.cc:115:5: error: unknown type name 'OnlineNnet3DecodingConfig'
    OnlineNnet3DecodingConfig nnet3_decoding_config;
    ^
k3.cc:202:26: error: no member named 'UpdateFrameWeights' in 'kaldi::OnlineNnet2FeaturePipeline'
        feature_pipeline.UpdateFrameWeights(delta_weights);
        ~~~~~~~~~~~~~~~~ ^
In file included from k3.cc:3:
In file included from kaldi/src/online2/online-nnet3-decoding.h:34:
In file included from kaldi/src/online2/online-endpoint.h:35:
In file included from kaldi/src/lat/kaldi-lattice.h:24:
In file included from kaldi/src/fstext/fstext-lib.h:23:
In file included from kaldi/src/fstext/context-fst.h:476:
In file included from kaldi/src/fstext/context-fst-inl.h:23:
In file included from kaldi/src/fstext/fstext-utils.h:31:
In file included from kaldi/src/fstext/determinize-star.h:121:
```
Any further advice is much appreciated :)

Thanks.

**Comment by tlc** [comment]
I **think** the build is broken in general, not for Centos.  I can't compile k3.cc on CentOS or Ubuntu.
> k3.cc:62:28: error: no type named 'OnlineNnet3DecodingConfig' in namespace 'kaldi'

This code with this reference was added 8 days ago here https://github.com/lowerquality/gentle/commit/798be8a861ee03831f0b363314f393d8e48f444c
Note the commit message:
> k3.cc with cuda initialization and compatible with older (stable) kaldi

3 days later there was a commit "_update kaldi version_".  Now the submodule link points to a very recent version
>  	kaldi @ 7ffc9dd

and "OnlineNnet3DecodingConfig" isn't in there.  According to https://github.com/gooofy/py-kaldi-asr/issues/4 , this went away over a year ago.

@strob can you confirm that you can build with a fresh pull?

@spinicrus if you need something now, I have a slightly older fork that builds on CentOS.  But I haven't yet pushed a install_deps.sh that will do yum installs.  https://github.com/tlc/gentle

**Comment by strob** [comment]
Hello! Thanks for this detailed and careful report. I must have had something cached when I thought I tested the submodule update. Apologies; should work now. Reopen if you have build issues.

**Comment by jph00** [comment]
I had to comment out the line:
```
cu_device.SetVerbose(true);
```
to get this to work (Ubuntu 18.04).

**Comment by wensle** [comment]
> I had to comment out the line:
> 
> ```
> cu_device.SetVerbose(true);
> ```
> 
> to get this to work (Ubuntu 18.04).

I had to do this as well (WSL Ubuntu 22.04.2 LTS).

PS: I've never expected for the fast.ai guy to have the same issue lol
