### ISSUE TITLE
Unable to compile Kaldi version after El Capitan

### ISSUE THREAD

**Issue by maxhawkins** [lowerquality/gentle#18]
Since upgrading to El Capitan I haven't been able to install the included version of Kaldi. There's an issue with gcc-fortran. Were you able to get it compiling?

**Comment by strob** [comment]
Yes, I am running El Capitan and have compiled Kaldi without issue. I'm testing a build now on the latest Kaldi commit, and will update the submodule if that works.

**Comment by strob** [comment]
One potential difference is that I have Cuda installed. I'm nervous that Cuda is leading to ```standard_kaldi``` and ```mkgraph``` binaries that will not be portable.

I'm not sure how to interpret this ```dtruss``` output:

```
stat64("/usr/local/cuda/lib/libcublas.7.5.dylib\0", 0x7FFF4FC68D08, 0x1)		 = 0 0
open("/usr/local/cuda/lib/libcublas.7.5.dylib\0", 0x0, 0x0)		 = 3 0
```
Perhaps the ```stat64``` call means that the binary will avoid cuda if it's not present on the system?

Would you do me a favor and test my [standard_kaldi build](http://lowerquality.com/gentle/standard_kaldi_0.02) on your system?

**Comment by maxhawkins** [comment]
OK, downloading now. Where is your server? The downloads are really slow from the Czech Republic.

**Comment by maxhawkins** [comment]
Bad news

```
dyld: Library not loaded: @rpath/libcublas.7.5.dylib
  Referenced from: /Users/max/projects/gentle2/./standard_kaldi_0.02
  Reason: image not found
fish: Job 1, './standard_kaldi_0.02 ' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by strob** [comment]
OK. I'm compiling again with ```./configure --static --static-math=yes --static-fst=yes --use-cuda=no``` and will see how that goes.

**Comment by strob** [comment]
Can you try [this build](http://lowerquality.com/gentle/standard_kaldi_0.02_nocuda)?

**Comment by maxhawkins** [comment]
That one works fine. :+1:

**Comment by strob** [comment]
Thanks for testing the binary, and very exciting that it works for you! 

I'm going to close this issue, because I think that building Kaldi on El Capitan is not a Gentle issue. There's been [activity](https://github.com/kaldi-asr/kaldi/commit/4235b99e93c266b1edebc60b7fe3ad5b112fcf46) that suggests attention to this upgrade on the Kaldi side of things, and now Gentle is using the latest version of Kaldi.

**Comment by maxhawkins** [comment]
OK. I'll test the compilation and reopen if there are any issues.
