### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-KJvqJr/

### ISSUE THREAD

**Issue by sutble** [lowerquality/gentle#182]
Hi, Im trying to install this library with a Mac running 10.13.4

Im running into the error listed above, the full install path is listed below

    ADITYGAR-M-448N:gentle aditygar$ ./install.sh
    Installing dependencies...
    Updating Homebrew...
    ==> Auto-updated Homebrew!
    Updated 1 tap (homebrew/core).
    ==> Updated Formulae
    teleport

    Warning: ffmpeg 4.0 is already installed and up-to-date
    To reinstall 4.0, run `brew reinstall ffmpeg`
    Warning: libtool 2.4.6_1 is already installed and up-to-date
    To reinstall 2.4.6_1, run `brew reinstall libtool`
    Warning: automake 1.16.1 is already installed and up-to-date
    To reinstall 1.16.1, run `brew reinstall automake`
    Warning: autoconf 2.69 is already installed and up-to-date
    To reinstall 2.69, run `brew reinstall autoconf` 
    Warning: wget 1.19.5 is already installed and up-to-date
    To reinstall 1.19.5, run `brew reinstall wget`
    Warning: python 3.6.5 is already installed and up-to-date
    To reinstall 3.6.5, run `brew reinstall python`
    Searching for pip
    Best match: pip 10.0.1
    Processing pip-10.0.1-py2.7.egg
    pip 10.0.1 is already the active version in easy-install.pth
    Installing pip script to /usr/local/bin
    Installing pip2.7 script to /usr/local/bin
    Installing pip2 script to /usr/local/bin

    Using /Library/Python/2.7/site-packages/pip-10.0.1-py2.7.egg
    Processing dependencies for pip
    Finished processing dependencies for pip
    The directory '/Users/aditygar/Library/Caches/pip/http' or its parent directory is not owned by the     current user and the cache has been disabled. Please check the permissions and owner of that   directory. If executing pip with sudo, you may want sudo's -H flag.
    The directory '/Users/aditygar/Library/Caches/pip' or its parent directory is not owned by the current  user and caching wheels has been disabled. check the permissions and owner of that directory. If  executing pip with sudo, you may want sudo's -H flag.
    Processing /Users/aditygar/Code/subtitles/gentle
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-CAI1sx/setup.py", line 2, in <module>
        from gentle import __version__
      File "gentle/__init__.py", line 3, in <module>
        from .forced_aligner import ForcedAligner
      File "gentle/forced_aligner.py", line 2, in <module>
        from gentle import kaldi_queue
      File "gentle/kaldi_queue.py", line 1, in <module>
        from queue import Queue
    ImportError: No module named queue

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-req-build-CAI1sx/

It seems a few other folks have had issues while installing the dependencies, however their solutions didn't work for me (Ive tried changing to pip2 in install_deps.sh and using git clone instead of downloading the repo).

Any help would be appreciated, Thanks!

**Comment by strob** [comment]
@sutble Please re-open if this doesn't work for you.
