### ISSUE TITLE
Gentle Stops Working on Second Pass of Server Mode, or Align.py With Longer Files

### ISSUE THREAD

**Issue by RomanScott** [lowerquality/gentle#186]
Hello,

I am running the latest version of Gentle on a Mac. In server mode, it runs through the first pass fine, but when it runs the second pass (the realignment phase), it gets to about half way and then it stops processing. There are no errors, but the k3 background processes all go away, except for one, and CPU usage drops to 0%. I think it might be a problem with the multipass.realign() function, standard_kaldi.py, or even the k3.cc file itself. 

This seems to only occur on longer audio files.

Thank you @strob 

**EDIT:** I did some more testing, and align.py also will not finish if the audio file is too long. (Do note the test files work fine, it's just longer files I have problems with. In addition, the 2017 version of Gentle did not have this issue)

**Comment by RomanScott** [comment]
I did some more investigating,
Actually the realign method fails only when it's provided too many unaligned words, like more than 100 words that's when it will abruptly stop.

@bit I know you have contributed a lot recently, would you be able to help out?

**Comment by strob** [comment]
This is vexing behavior.
Do you have a test case you could link to on http://gentle-demo.lowerquality.com? 

To confirm: you're running the latest version of Gentle from Git, on a reasonably up-to-date macOS with 8+gb RAM? 

I've noticed that the Adjacency Optimizer can be quite time-consuming on highly misaligned files, but haven't seen an issue like this yet.

**Comment by RomanScott** [comment]
@strob

Hello. I am running on the latest version of Gentle, on an up-to-date macOS.

When I run the audio file on gentle-demo, the realignment phase still only reaches 50%, but it actually finishes the transcription (with a lot of words missing), rather than just hanging on macOS. The problem still exists, but it just finishes with many unaligned words instead of just indefinitely waiting on a Mac. Here is the link to the test case (http://gentle-demo.lowerquality.com/transcriptions/948f6025/). 

The file I am testing with is Shape of You by Ed Sheeran (with transcript as the lyrics to the song).

I don't think the issue is with the Adjacency Optimizer. I believe the issue is somewhere within the realign() method in multipass.py, around lines 78-80, standard_kaldi.py (maybe the push_chunk method) or in k3.cc, lines 184-214. I deduced this after some debugging, I ran some print statements and the program seems to stop around the push_chunk method, although I could be incorrect.

**Comment by bit** [comment]
in push_chunk gentle/standard_kaldi.py

  cnt = len(buf)/2

is buf always a multiple of 2? during python3 migration this would have changed, can you try to change that line to 

  cnt = int(len(buf)/2)

**Comment by bit** [comment]
even for even numbers the current code produces N.0 instead of N.
pull request to fix this: https://github.com/lowerquality/gentle/pull/189

**Comment by RomanScott** [comment]
@bit

Hello, I am not at home to check if this fix works at the moment, have you been able to confirm that it works?

**Comment by RomanScott** [comment]
@bit 
I tested your code and it does not fix the issue.

**Comment by RomanScott** [comment]
@strob @bit

After some more testing, it seems to be that the realignment process stops in the k3 file. I don't believe there is a problem with the Python code, but probably the C++ file itself. It seems like push_chunk() halts or fails in the C++ code (lines 184-214). However, I am not sure how to get a stacktrace out of this C++ file. Could either of you investigate further?

**Comment by strob** [comment]
Hi,

I suspect this is a RAM issue. If you are doing alignment, and have the full language model installed, you may want to run Gentle with a flag like `--ntranscriptionthreads=0` to avoid loading the full LM.

Please check RAM usage while running to confirm that you have enough available.

**Comment by RomanScott** [comment]
@strob 

I don't believe RAM is an issue. I do not have the full language model installed, and when I check the RAM usage, it tells me that k3 is using around 200MB of RAM, and my total RAM usage is about 4GB out of an 8GB computer.

**Comment by RomanScott** [comment]
@strob 

Have you been able to come up with a solution yet? This issue is extremely high-priority for me, and it is critical for my work. Could I provide you with some sort of compensation in order to get this resolved quicker?

**Comment by strob** [comment]
Hi Roman,

I'm sorry you're having trouble with Gentle. The acoustic model is not
designed for musical alignment, and it's possible that a pathological
lattice is constructed on the basis of the song. I am working on
reproducing your issue and hope to have a fix shortly.

**Comment by RomanScott** [comment]
@strob 

Thank you very much for your help. I don't think the issue is limited to songs per se, but just audio that has a high amount of unaligned words after the first pass (for example, noisy or mumbled audio), but I'm not sure because the only audio I have been able to find with high unalignment rates were ones with music. In addition, the older fork of Kaldi (the one from 2017) did not have this issue present. I'm fine if Gentle is not able to find all of the words, I would just like the alignment process to finish.

Thank you for your diligence in regards to fixing this issue and your patience, and I appreciate you creating this software, it's helping a lot of people!

**Comment by RomanScott** [comment]
@strob 

Any updates or progress in regards to the resolution of this issue?

**Comment by reacuna** [comment]
Hello,
I'm also seeing this issue on a non-song context. I'm currently uploading it to have a test case on http://gentle-demo.lowerquality.com.
Is there anything that I can do to help with this issue?
Thanks,

**Comment by reacuna** [comment]
This is the uploaded test case: http://gentle-demo.lowerquality.com/transcriptions/ce853c65 (which seems broken on the UI, but maybe you have some more info on the backend?)

**Comment by reacuna** [comment]
I've been running this same file locally and after the 'Transcribing' pass the results are `INFO:root:398 unaligned words (of 2587)`. From there, it stalls in the 'Aligning' phase at `{'percent': 0.30656934306569344}`.

**Comment by jpcanepa** [comment]
After diagnosing this with @reacuna, we found the problem. 

The wrapper around k3 (gentle/standard_kaldi.py) works by pushing messages though the subprocess stdin with the ["write" method of the stream](https://github.com/lowerquality/gentle/blob/893e09b14eabff3a6ec2ff87db0499bc3fd2a213/gentle/standard_kaldi.py#L37). That is _actively discouraged_ [in the python documentation](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.stderr) precisely because it can block if the kernel pipe buffer ever fills up. In that scenario, k3 [calls fread](https://github.com/lowerquality/gentle/blob/893e09b14eabff3a6ec2ff87db0499bc3fd2a213/ext/k3.cc#L194) but blocks forever.

The python documentation suggests using _communicate_ instead of write/read, but that waits for the process to finish, which in the current incarnation of the code won't work (but with my limited understanding of how the k3 binary is being used in the alignment phase, should be _possible_).

We worked around the problem by, instead of pushing the chunk through of the subprocess stdin, writing it to a file specific for that subprocess (like `comm_<pid>`), and reading from that in k3. I don't have the code at hand to make a pull request, but you can look at [this commit](https://github.com/descriptinc/gentle/commit/d640de7e74dbd608cc6dd644631020b716dc537c) for the file handling stuff (includes some logging and modernization too). [Later](https://github.com/descriptinc/gentle/commit/83a680757f6795ff9e74388581c4093de51a1531) we removed the logging, made sure to cleanup after the process finishes (and updated a little the use of C++).

**Comment by bit** [comment]
does it still block if you flush after the write?

```
--- a/gentle/standard_kaldi.py
+++ b/gentle/standard_kaldi.py
@@ -35,6 +35,7 @@ class Kaldi:
         cnt = int(len(buf)/2)
         self._cmd(str(cnt))
         self._p.stdin.write(buf) #arr.tostring())
+        self._p.stdin.flush()
         status = self._p.stdout.readline().strip().decode()
         return status == 'ok'
```

**Comment by reacuna** [comment]
@bit yes, it does.

**Comment by adamelmore** [comment]
Fwiw, I got around this issue by simply passing `bufsize=0` as a param to the `Popen` call:
```
self._p = subprocess.Popen(
            cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=STDERR, bufsize=0
        )
```
(Sorry for the non-functional format changes, I use black for auto-formatting.)

**Comment by Jasonbaby** [comment]
setting bufsize to 0 can not help in my case, I still suffer this problem.
Did anyone fix it?
