### ISSUE TITLE
Python 3.5 on Linux produces UTF-8 error

### ISSUE THREAD

**Issue by dhuv** [lowerquality/gentle#188]
I am getting the following when running the CLI command "python3 align.py texfile.txt media.mp3"

I am running Debian 9.4 which installs Python 3.5 so wondering if Gentle was tested with 3.5 (especially on Linux).

I tested with a text file that works on your Mac package on the latest OSX. Same error no matter what.

------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "align.py", line 47, in <module>
    transcript = fh.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
------------------------------------------------------------------------------------------

**Comment by bit** [comment]
is the text file your provide encoded in utf-8?

**Comment by bit** [comment]
you are passing the files in the wrong order.
instead of `python3 align.py texfile.txt media.mp3` you have to run `python3 align.py media.mp3 texfile.txt`

**Comment by dhuv** [comment]
@bit Thank you, the arguments where in the wrong order. The file was UTF-8, I verified that.
