### ISSUE TITLE
Bad link for openfst

### ISSUE THREAD

**Issue by dhuv** [lowerquality/gentle#193]
The install.sh script tries to download openfst-1.6.5.tar.gz from the following link and fails.

http://www.openslr.org/resources/2/openfst-1.6.5.tar.gz

Apparently that needs to be updated.

**Comment by dhuv** [comment]
FYI, I was able to get past this by running "apt-get install libfst4 libfst-tools" and it got past that point.

Perhaps we can put this in the install_deps.sh?

**Comment by dhuv** [comment]
I had to change the link in gentle/ext/kaldi/tools/Makefile to be www.openfst.org instead of openfst.cs.nyu.edu. This is in the Kaldi repository so I will open an issue and pull request there.

**Comment by wakandan** [comment]
I'm still having this bug today. Seems like it's not being fixed yet
