### ISSUE TITLE
Alignment stuck at the last step

### ISSUE THREAD

**Issue by bluemonk482** [lowerquality/gentle#197]
I failed to install kaldi following the instruction provided by gentle, therefore I copy-pasted another kaldi folder (which I managed to install successfully) to `ext`. Running `server.py` and `align.py`, it seems it is working. However, it always stops at the last step:

`INFO:root:82/83`

This happens no matter I call the REST API or use `aligner.transcribe()` in `align.py`.

**Comment by adamelmore** [comment]
Possible duplicate of #186? @bluemonk482 could you try pulling latest `master` and see if your issue persists?

**Comment by bluemonk482** [comment]
Thanks @adamelmore ! Problem resolved. I will close the issue now. 

Btw Statmuse is the shit! I have followed it since its very beginning. 👍
