### ISSUE TITLE
Python 3.7 causes errors

### ISSUE THREAD

**Issue by dariusk** [lowerquality/gentle#198]
I am far from a Python expert but it seems like there is a lot of code in this that works in 3.6 but not 3.7 ("async" is used as a variable name in `serve.py` for one, and I _think_ that's a reserved word in 3.7). I would make a PR but I'm not sure I have a complete handle on what is going on. Would it make sense to specify 3.6.* as a required version of `python3`?

**Comment by lvscar** [comment]
Hello @dariusk , I like gentle project and meet the same problem too, have submitted a [PR](https://github.com/lowerquality/gentle/pull/206).

**Comment by dariusk** [comment]
@lvscar Thanks :)
