### ISSUE TITLE
How to improve aligning accuracy for long time content

### ISSUE THREAD

**Issue by lvscar** [lowerquality/gentle#207]
Hi , Thanks for the great works of gentle!  It's very helpful for language learning. I'm fascinated with it.

I used source code installation on Mac OS.  After fixed a minor Python 3.7 incompatible problem, gentle work well on my environment for short speech recording.

I have tried to use gentle to align an 11 hours audio book with it textual content.  The process took few hours to run, but finally ended errorless with a 50MB JSON file. 

When I examined the aligning result of gentle, I found an interesting phenomenon.  At the beginning of few paragraphs, the accuracy is perfect. But the accuracy was declining along with the ratio of whole content.  At half length of the book, the text&audio deviation was 30+ seconds on average. 

Could you give me some suggestion for how to improve the accuracy for long time content?  Will be helpful if add more alignment pass? (I found it is a two pass setup now )

**Comment by strob** [comment]
Wow, I think you win the award for longest file aligned with Gentle!

My first thought is that the 8khz audio downsampling may be introducing timing error. Can you check if “a.wav” has a matching duration to your original file? How have you been testing the alignment? There could also be an issue with the JS preview at that length. 

I don’t think the multi-pass is at fault.

**Comment by lvscar** [comment]
Although the wav file and source mp3 file have the same length ( just 1 second distinction for 11 hours).  The aligning test result using the wav file is almost flawless!  

Thanks @strob for the clue. 

If you have some improving strategy , I would try to contribute more to improve the experience for aligning long time audio file.
