### ISSUE TITLE
alignment stuck

### ISSUE THREAD

**Issue by chuckcho** [lowerquality/gentle#211]
Similar to https://github.com/lowerquality/gentle/issues/197, the alignment gets stuck at the last step (this is a rather short audio clip <5 min)

```
python3 align.py  -o ../out.json ../00000256_01.wav ../00000256_01.txt
INFO:root:converting audio to 8K sampled wav
INFO:root:starting alignment
INFO:root:1/17
INFO:root:2/17
INFO:root:3/17
INFO:root:4/17
INFO:root:5/17
INFO:root:6/17
INFO:root:7/17
INFO:root:8/17
INFO:root:9/17
INFO:root:10/17
INFO:root:11/17
INFO:root:12/17
INFO:root:13/17
INFO:root:14/17
INFO:root:15/17
INFO:root:16/17
(hours of waiting and nothing happens)
```

I'm using the latest version (cloned today) on Mac. Running with `--log DEBUG` param doesn't seem to provide anything helpful to troubleshoot this.

Somehow if I run the pre-built Mac application, I don't see this problem. Any help please?

**Comment by yya518** [comment]
I encounter this same problem with the latest release. The align.py got stuck in the middle of the alignment process. If I kill the process and restart the alignment, the program will run smoothly but it will happen again on another transcript/audio alignment instance later (I have a few hundreds pair of transcript/audio examples). Seems pretty random to me. Any idea to fix the problem?

**Comment by jarivk** [comment]
I am facing same issue. Its very annoying.
