### ISSUE TITLE
https://lowerquality.com/ SSL cert has expired

### ISSUE THREAD

**Issue by deybhayden** [lowerquality/gentle#219]
Running `install_models.sh` fails right now.

Tries to download  https://lowerquality.com/gentle/kaldi-models-0.03.zip and the Let's encrypt cert is expired and the install fails (cert expired on March 2nd looks like).

**Comment by iskunk** [comment]
The site appears to have a current Let's Encrypt SSL cert at this time (expires on 2020 March 8).

Could you check that the download is working for you now?
