### ISSUE TITLE
Error in build script

### ISSUE THREAD

**Issue by danpovey** [lowerquality/gentle#225]
https://github.com/lowerquality/gentle/blob/ce6873d8dfa3278e060fc74366fb54282b414ea3/ext/install_kaldi.sh#L9

You shouldn't "make clean" before running "configure".

**Comment by strob** [comment]
Thank you @danpovey! I've pushed this in a928cac4a96dd1510ca996926c44ea0ea74453aa and hope it addresses the issue you were seeing. I think that's in there from some debugging after performing an upstream update...
