### ISSUE TITLE
Expired SSL Certificate in site

### ISSUE THREAD

**Issue by Petemir** [lowerquality/gentle#242]
Hello, I know this is note code-related but couldn't find any contact form/info on the site. Gentle's webpage currently has an expired/invalid HTTPS certificate so it shows an error on entering.

**Comment by MaximVol** [comment]
The expired certificate blocks installation of Gentle.
Maybe the Kadi models file can be uploaded to Github, and installation script can be corrected to download this file from a new URL?
[https://www.dropbox.com/s/ooyjpya58c57w7h/kaldi-models-0.03.zip?dl=1](url)

**Comment by BayesForDays** [comment]
I've been getting this error as well, so I updated the install script to add `--no-check-certificate` in the `wget` command, but I'd love to not do this. I agree it'd be great if the model file could be on github, assuming the size is manageable.
