### ISSUE TITLE
How to run it in Colab?

### ISSUE THREAD

**Issue by qo4on** [lowerquality/gentle#248]
I do the following, but the installation is going forever:
```
!git clone -q https://github.com/lowerquality/gentle.git > /dev/null
%cd /content/gentle
!./install.sh
```

**Comment by Mistobaan** [comment]
Building Kaldi in Colab will take forever. Better to build the project somewhere else and upload it on Colab with Google Drive.

**Comment by qo4on** [comment]
Why?

**Comment by Mistobaan** [comment]
Colab has only one or two CPUs and limited disk space and is pre-emptive, so the instance could die at any time in your 4h compilation period.

**Comment by qo4on** [comment]
Yes, Colab has 2 CPUs, but when it runs you get all its power. I saw only a few seconds delay when I run a cell because of pre-emptiveness. 37 GB of free disk space is more than enough I think.
Gentle needs 4 hours to compile? Are you sure? Is there a compiled version?

**Comment by Mistobaan** [comment]
No. It doesn't have a pre-built package for Linux. And I never tried running Docker in colab.  Yes it takes a while, and Kaldi is the slow path not gentle.
