### ISSUE TITLE
kaldi has been installed,how to install gentle？

### ISSUE THREAD

**Issue by sunnnnnnnny** [lowerquality/gentle#269]
So how do I modify ./install.sh or configure other files

**Comment by natelawrence** [comment]
Hello, Sunny, 

I'm only your fellow user, but can tell you this much: 

You can refer to the Gentle ReadMe here: https://github.com/lowerquality/gentle/blob/master/README.md

----------     ----------     ----------     ----------     ----------     ----------     ----------     ----------     

As for myself, I use [Docker Desktop](https://www.docker.com/products/docker-desktop) on Windows and use [Kitematic](https://kitematic.com/) to give Docker a GUI for me to install versions of Gentle, start them up, close them, uninstall them, etc.

Please write back if you decide to try Docker and are having difficulties getting going. 

Let's get you up and running.

**Comment by sunnnnnnnny** [comment]
OK. I have never used docker, I don’t know anything about docker, and I am ready to try it

**Comment by natelawrence** [comment]
What operating system are you using?

**Comment by sunnnnnnnny** [comment]
Linux ubuntu 4.4.0-116-generic

**Comment by MeghaRajpara** [comment]
> 
> 
> Hello, Sunny,
> 
> I'm only your fellow user, but can tell you this much:
> 
> You can refer to the Gentle ReadMe here: https://github.com/lowerquality/gentle/blob/master/README.md
> 
> As for myself, I use [Docker Desktop](https://www.docker.com/products/docker-desktop) on Windows and use [Kitematic](https://kitematic.com/) to give Docker a GUI for me to install versions of Gentle, start them up, close them, uninstall them, etc.
> 
> Please write back if you decide to try Docker and are having difficulties getting going.
> 
> Let's get you up and running.

Could you run it on docker? I am trying to run it on docker but couldn't run it.

**Comment by lilgandhi1199** [comment]
https://github.com/lowerquality/gentle/issues/251#issuecomment-731702538


Just run these additional commands.
I got it working easily like this is many versions of ubuntu

**Comment by MeghaRajpara** [comment]
> 
> 
> [#251 (comment)](https://github.com/lowerquality/gentle/issues/251#issuecomment-731702538)
> 
> Just run these additional commands.
> I got it working easily like this is many versions of ubuntu

I could run it. Do you have any idea about it how to run in Linux OS server using Putty?
