### ISSUE TITLE
Remove sil phones

### ISSUE THREAD

**Issue by maxhawkins** [lowerquality/gentle#27]
The current alignment process includes some leading and trailing silence in the output offsets. It would be better to return tighter bounds around each spoken word.

I think we can get a lot closer if we use the phone-level alignment and ignore remove silence phones.

For instance, this one can just start at 17.77:

```json
{
  "case": "success", 
  "end": 17.85, 
  "phones": [
    {
      "duration": 3.62, 
      "phone": "sil"
    }, 
    {
      "duration": 0.08, 
      "phone": "ay_S"
    }
  ], 
  "alignedWord": "i", 
  "start": 14.15, 
  "word": "I"
}, 
```

**Comment by strob** [comment]
Agree. This would be an easy post-processing step in Python. Two issues:

 * The current JSON format doesn't accommodate out-of-word phonemes very well. We could address this by simply eliminating silence, but we may want a place to put those phonemes that weren't mapped to words (including those where "case" != "success").

 * Until we deal with #10, I have some larger doubts about word boundaries.

**Comment by maxhawkins** [comment]
I'm not sure what the common use-case for the phonemic transcription is. Maybe it would be better to separate them from the word transcription? It would be easy enough to calculate which phonemes map to words on the client-side.
