### ISSUE TITLE
localhost refused to connect

### ISSUE THREAD

**Issue by casillano** [lowerquality/gentle#270]
```
sudo docker run -P lowerquality/gentle
INFO:root:gentle 0.10.1
INFO:root:listening at 0.0.0.0:8765

INFO:root:SERVE 8765, 0.0.0.0, 1
INFO:root:about to listen
INFO:root:listening
```
I tried connecting to http://localhost:8765 but it says connection refused. Just a few days ago it was working fine

**Comment by casillano** [comment]
I checked Docker Desktop and it seems that the site shows up on localhost:32768 instead. Command line still shows it listening on 8765.

**Comment by casillano** [comment]
I checked Docker Desktop and it seems that gentle listens on a different port every time I run it. It started at port 32768. How do I fix this?

**Comment by natelawrence** [comment]
I'm glad you tracked down the switching port numbers with Docker.

If you use [Kitematic](https://kitematic.com/), you can go into: 
container name > Settings > Hostname/Ports to see which port your container is talking to.

![image](https://user-images.githubusercontent.com/2601664/90327768-f38f0880-df4b-11ea-930a-badc81a6d2c7.png)

**Comment by casillano** [comment]
Thanks, that helped. It seems that `docker run -p 8765:8765 lowerquality/gentle` ensures that the public ip is always http://localhost:8765
