### ISSUE TITLE
Help with phoneme meanings

### ISSUE THREAD

**Issue by 15leesan** [lowerquality/gentle#274]
What do the phoneme codes actually mean? The [model](https://github.com/lowerquality/gentle/wiki/Model) page says:
> After recognition, the speech is split into phonemes using a version of The CMU Pronouncing Dictionary. The phoneme set is based on ARPAbet.

However, ARPAbet phonemes look like this: `AA, CH, N` and so on, and gentle's phonemes look like this: `t_B, uw_I, d_I, ey_E` and so on.
Are the final character and underscore important i some way? Does `ey_E` (gentle) mean anything different to `EY` (ARPAbet)?

**Comment by beckgoodloe** [comment]
Hi there, I'm just another amateur user of Gentle but I might be able to clear some things up. The general structure of the phoneme returned by Gentle has a little bit more information than the ARPAbet phonemes, but still follows the same phoneme structure.

Below I've included a list that I believe encompasses all of the phonemes returned by Gentle (except for "oov" which I believe is "out of vocabulary")

<img width="245" alt="Screen Shot 2020-08-13 at 2 20 24 PM" src="https://user-images.githubusercontent.com/6676634/91622325-3abdc600-e95c-11ea-9a5c-5c930ca65660.png">

After the underscore in Gentle's returned phoneme are B, I, or E which I have been assuming corresponds to the phonemes position in the word (either beginning, intermediate, or end). Let me know if that helps at all!

**Comment by 15leesan** [comment]
@beckgoodloe thank you so much, that's exactly what I was looking for (especially the B, I and E bit)!
