### ISSUE TITLE
RuntimeError: No resource directory /Volumes/Elements/mispronounciation_detection/gentle/exp.  Check GENTLE_RESOURCES_ROOT environment variable?

### ISSUE THREAD

**Issue by viditjain99** [lowerquality/gentle#283]
I followed the installation process as mentioned in the README.md file and cloned the repository using the command: git clone --recurse-submodules https://github.com/lowerquality/gentle.git, but still, when I run serve.py I get the error. Those who have managed to install on python please help.

**Comment by prlabu** [comment]
Same here! Trying the simple install protocol from the README. 


```
git clone https://github.com/lowerquality/gentle.git
cd gentle
./install.sh
python3 align.py audio.mp3 words.txt
```

macOS Big Sur 11.2.2
Mac Pro Late 2013

**Comment by prlabu** [comment]
@viditjain99 Were you able to find a fix?
