### ISSUE TITLE
List of phones Gentle uses and what they map to

### ISSUE THREAD

**Issue by SuperSonicHub1** [lowerquality/gentle#302]
I'm trying to use Gentle to create a lip-flap animator, and while the software works for me, I don't really know how to use its outputs.

In my program, each phoneme of the English language will be assigned to a photo, and so I need to know what each phoneme uttered is. Gentle gives me this data, but the phoneme names don't seem to match [any digitization of, say, the IPA](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet#Computer_support). Instead, I get obscure phoneme names like `dh_B` and `ah_E`. `dh` is usually transcribed as `th` so this caught me off-guard at first, and I have no idea what `E` means.

If I could get a list of all of Gentle's possible phonemes and their mappings to the IPA, that would make my life a lot easier.

**Comment by strob** [comment]
The suffixes (B, I, E) stand for "beginning", "middle", and "end" (of the word in which they appear)

**Comment by SuperSonicHub1** [comment]
@strob Thanks! Now all I need are a list of phonemes.

**Comment by tscizzle** [comment]
I was just checking this repo to ask the same exact thing! How timely.

Even if the phoneme list comes from somewhere else, like Kaldi, any clue as we might go about finding it, or relevant documentation?

**Comment by SuperSonicHub1** [comment]
Found it!
http://www.speech.cs.cmu.edu/cgi-bin/cmudict
Thanks, [carykh](https://youtu.be/28U6EwfKois?t=331)!
