### ISSUE TITLE
Alignment struggles at 20-second intervals

### ISSUE THREAD

**Issue by strob** [lowerquality/gentle#35]
The "grain" of arbitrary, 20-second endpointing results in a high propensity for multi-word error around the seams.

<img width="653" alt="screen shot 2015-11-26 at 10 36 03 am" src="https://cloud.githubusercontent.com/assets/208551/11429204/9be97f56-9429-11e5-89bf-2a97136de554.png">

**Comment by maxhawkins** [comment]
I've prepared a smaller [https://drive.google.com/file/d/0B3wEP3UhFKM-bWZhazlNREIyRkk/view](test clip) that we can use to track down this issue. The aligner should have no trouble aligning the audio from 0:15 to 0:20 but it seems to be having trouble.

**Comment by strob** [comment]
Multi-pass alignment and overlap substantially resolves this.
