### ISSUE TITLE
"damaged and can't be opened" message on startup

### ISSUE THREAD

**Issue by maxhawkins** [lowerquality/gentle#43]
<img width="532" alt="screen shot 2015-12-01 at 7 39 03 am" src="https://cloud.githubusercontent.com/assets/28565/11494016/b1ff7cae-97fe-11e5-92af-6b25dda5ca48.png">

I get this message with the 0.5.0 dmg on my mac running El Capitan

**Comment by strob** [comment]
Can you verify the md5sum?
```
35e9fb9933f345f4e94aa6630c556d4a  gentle-0.5.0.dmg
```

**Comment by strob** [comment]
I can verify that [this one](http://lowerquality.com/gentle/gentle-0.5.0.dmg) is correct. Weird that github doesn't show you the hash.

**Comment by strob** [comment]
I cannot reproduce this bug.

**Comment by maxhawkins** [comment]
That's the md5 I have. Maybe it's picking up some library I have installed on my system?

This seems like the same issue:
https://groups.google.com/forum/#!msg/pyinstaller/XXYGHCKNFoA/TCjEDmthvNkJ

**Comment by maxhawkins** [comment]
Maybe we need to sign up for the dev program and get a cert?

**Comment by strob** [comment]
Seems not to be a problem with 0.7.0. Spooky!
