### ISSUE TITLE
error on transcribe without graph/ dir

### ISSUE THREAD

**Issue by maxhawkins** [lowerquality/gentle#56]
Attempting to transcribe (not align) when there is no graph/ model directory raises an exception rather than failing gracefully. People with the standard PROTO_LANGDIR configuration will see an error here.

**Comment by srubin** [comment]
Did you train/compute the general-purpose HCLG.fst on your own, or did you get it from elsewhere (e.g.,  http://kaldi-asr.org/downloads/all/egs/fisher_english/s5/ ). If you got it elsewhere, could you point me to the file you're using?

**Comment by strob** [comment]
We're using the Fisher English online_nnet2 from Kaldi [here](http://kaldi-asr.org/downloads/build/2/sandbox/online/egs/fisher_english/s5/exp/tri5a/graph/archive.tar.gz) (unzip archive.tar.gz to a "graph" directory).
