### ISSUE TITLE
C++ Exceptions Hard To Trace

### ISSUE THREAD

**Issue by maxhawkins** [lowerquality/gentle#63]
We're not capturing stderr from standard_kaldi so it's really hard to figure out what went wrong when there's a problem. I know we disabled it because of some problem with the Mac app packaging. However, I can't remember the specific issue. Is it safe to re-enable stderr so we can get better exceptions?

**Comment by strob** [comment]
AFAICT, we can't emit any stdout/stderr messages from our DMG. They'll work for a while from Console.app, and then the pipe will randomly block and our program will silently fail. I haven't found much documentation about this.
