### ISSUE TITLE
view_alignment "update" race condition

### ISSUE THREAD

**Issue by strob** [lowerquality/gentle#67]
On very long alignments, ```get_json("align.json")``` may hit the file as it's being written, leading to a (fatal) parse error.

<img width="294" alt="screen shot 2016-01-06 at 6 58 29 pm" src="https://cloud.githubusercontent.com/assets/208551/12161160/88117242-b4a7-11e5-9740-7871236cd52f.png">

We should either catch the exception, be smarter about clobbering ```align.json``` on the server, or both.

**Comment by maxhawkins** [comment]
`mv` is atomic in POSIX. Let's write to a temp file and overwrite.
