### ISSUE TITLE
Word skips (drops)

### ISSUE THREAD

**Issue by whitecolor** [lowerquality/gentle#90]
I've noticed that aligner drops some words from transcript, actually they are in audio. Its not big amount less then 0.5% (for example 7 words from 1500), is something can be done about it, maybe some approximation if user is 100% sure that words are in audio?

**Comment by strob** [comment]
Can you send a test case?

**Comment by whitecolor** [comment]
audio: https://s3.amazonaws.com/bbooks_media_back/eda6ec9d7d30cd383065f384a29dbdb8.mp3
transcript: https://gist.github.com/whitecolor/8f7171e8b1a599fd6c68eb37c4154c38

This is the result:
http://gentle-demo.lowerquality.com/transcriptions/60fd0e67/

if to add ` Include disfluencies` option it skips less (but adds some `uh`)

Btw:
1) How this options `such as  Include disfluencies` can be included via API?
2) Is it possible to do async transcript via API?

**Comment by strob** [comment]
We are always trying to increase alignment rates in Gentle, but unfortunately this isn't a "bug" _per se_, so much as it's an indication that we simply can't align all of the words all of the time. Closing this issue.

1. adding a ```disfluency=true``` GET request should enable disfluencies;
2. not officially supported, sorry

**Comment by whitecolor** [comment]
That is ok, I just approximate timing for such words)

> adding a disfluency=true GET request should enable disfluencies;

you mean to POST request (which is `async=true`)?
