### ISSUE TITLE
i could not execute serve.py , it gives an error in multipass.py file at line 15

### ISSUE THREAD

**Issue by saquibajaz** [lowerquality/gentle#91]
i installed this aligner on linux
which at last shows this:

```
Fetched 5,296 kB in 1min 6s (80.2 kB/s)                                        
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ffmpeg is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ffmpeg' has no installation candidate
```
after that when i execute **python serve.py** it gives this error:
```
Traceback (most recent call last):
  File "serve.py", line 23, in <module>
    from gentle import multipass
  File "/home/ucertify/Desktop/gentle/gentle/multipass.py", line 15, in <module>
    with open(vocab_path) as f:
IOError: [Errno 2] No such file or directory: 'PROTO_LANGDIR/graphdir/words.txt'
```
Please help me...

**Comment by strob** [comment]
Looks like your version of Debian or Ubuntu is too old. Only Ubuntu 15.10
and later are officially supported.

**Comment by Saxenauts** [comment]
@strob :  That can't be true. I installed gentle on Ubuntu 14.04 successfully, although it isn't giving immaculate performance. Maybe that is because I installed Kaldi without CUDA enabled. But I can do alignment on my machine successfully. 

@saquibajaz : ffmpeg isn't officially supported on 14.04, so install it this way if yours is 14.04
```
sudo add-apt-repository ppa:mc3man/trusty-media
sudo apt-get update
sudo apt-get dist-upgrade

sudo apt-get install ffmpeg
```

**Comment by saquibajaz** [comment]
i updated my ubuntu version and it worked....thanks a lot...@strob
now i want to automate the process...means i want to generate multiple json in a loop..so where i had to make changes in the file ????

**Comment by strob** [comment]
Glad you were able to get Gentle working. 
Look into bash scripting for your automation needs.

**Comment by saquibajaz** [comment]
@strob i am not able to find the exact file. i am very new to python so can you please provide me some help.
or i may use the REST API but can i use this REST API in PHP
if "yes" then how????

**Comment by saquibajaz** [comment]
when i use this REST API on terminal is gives null
```ucertify@ucertify-Lenovo-G580:~/Desktop/gentle$ curl -F "audio=@029vC.wav" -F "transcript=@029vC.txt" "http://localhost:8765/transcriptions?async=false"
nullucertify@ucertify-Lenovo-G580:~/Desktop/gentle$ ```

**Comment by strob** [comment]
Looks like you used an "@" instead of a "<" for the transcript. See
```examples/gentle_curl.sh``` for correct usage.
