### ISSUE TITLE
Can I adjust the data represented within align.csv?

### ISSUE THREAD

**Issue by webtech1980** [lowerquality/gentle#93]
Hello again, I see that align.json has the timestamp data for phonemes. I was wondering if there is a way to get align.csv to also list that info. Maybe by adjusting the why in which the data is being parsed? Any thoughts on the best way to go about this?

**Comment by strob** [comment]
I would consider a patch that exposes phoneme timing in a CSV, but hierarchical data (phonemes are in words) just seem so much more sensible in JSON. Closing for now, but feel free to reopen if you have ideas for how the CSV should look.
